m = int(input('Enter first number : '))
n = int(input('Enter second number : '))
print (m,'+' ,n , '=',m+n )
print (m,'-' ,n , '=',m-n )
print (m,'x' ,n , '=',m*n )
print (m,'/' ,n , '=',m/n )
print (m,'//' ,n , '=',m//n, 'and remainder will be',m%n )
print (m, 'raise to power', n , 'will be',m ** n )